# Created using wingetcreate 1.9.4.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: Microsoft.DSC
PackageVersion: 3.1.0-preview.1
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: dsc.exe
  PortableCommandAlias: dsc
Commands:
- dsc
FileExtensions:
- dsc.json
- dsc.yaml
- winget
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/PowerShell/DSC/releases/download/v3.1.0-preview.1/DSC-3.1.0-preview.1-x86_64-pc-windows-msvc.zip
  InstallerSha256: A10D5ED545ACD56F3DE0FC6736265B897340511E608611662FC530FFAA3EE029
ManifestType: installer
ManifestVersion: 1.9.0
ReleaseDate: 2025-03-18
