# Created using wingetcreate 1.9.4.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.9.0.schema.json

PackageIdentifier: sbt.sbt
PackageVersion: 1.10.7
PackageLocale: en-US
Publisher: Lightbend, Inc.
PublisherUrl: https://www.lightbend.com/
PublisherSupportUrl: https://www.scala-sbt.org/support.html
PrivacyUrl: https://www.lightbend.com/legal/privacy?_ga=2.106952203.969622968.1639120972-1490489665.1639120972
PackageName: sbt
PackageUrl: https://www.scala-sbt.org/
License: Apache-2.0
LicenseUrl: https://github.com/sbt/sbt/blob/HEAD/LICENSE
ShortDescription: A build tool for Scala, Java, and more
Moniker: sbt
Tags:
- admin
- functional
- java
- language
- programming
- sbt
- scala
Documentations:
- DocumentLabel: Wiki
  DocumentUrl: https://github.com/sbt/sbt/wiki
ManifestType: defaultLocale
ManifestVersion: 1.9.0
